version: "3"

services:
  thermo:
    environment:
      - TZ='Europe/Amsterdam'
      - VERWARMING_DB_IP=192.168.0.125
      - VERWARMING_DBNAME=verwarming
      - VERWARMING_DBUSER=postgres
      - VERWARMING_DBPASS=docker
    restart: unless-stopped
    build: "./"
    privileged: true
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  verwarmcontroller:
    environment:
      - TZ='Europe/Amsterdam'
      - VERWARMING_DB_IP=192.168.0.125
      - VERWARMING_DBNAME=verwarming
      - VERWARMING_DBUSER=postgres
      - VERWARMING_DBPASS=docker
      - AIRCO_IP=http://192.168.0.135
    build: "./controller"
    restart: unless-stopped
    ports:
      - "6543:5000"
    networks:
      new:
        aliases:
          - verwarmcontroller
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  verwarmonoff:
    environment:
      - TZ='Europe/Amsterdam'
      - VERWARMING_ONOFF_RPI=http://192.168.0.125:8000/
      - VERWARMING_CLOSING_OFFSET=0.2
      - VERWARMING_HEATING_OFFSET=0.7
      - AIRCO_VERWARMING_HEATING_OFFSET=0.4
      - VERWARMING_SMART_HEAT=False
      - VERWARMING_ONOFF_LON=4.60
      - VERWARMING_ONOFF_LAT=51.87
      - VERWARMING_ONOFF_API="b3e2781468f747d3a2781468f7d7d30b"
      - AIRCO_OUTSIDE_TEMP_IP="192.168.0.137"
      - AIRCO_HEATING_TEMP_INCREASE=1
    build: "./onoffscripts"
    restart: unless-stopped
    privileged: true
    network_mode: "host"
    depends_on:
      - verwarmcontroller
      #- thermo
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nefitread:
    environment:
      - TZ='Europe/Amsterdam'
      - VERWARMING_ONOFF_RPI=http://192.168.0.125:8000/
      - VERWARMING_DB_IP=192.168.0.125
      - VERWARMING_DBNAME=verwarming
      - VERWARMING_DBUSER=postgres
      - VERWARMING_DBPASS=docker
    build: "./read_nefit_data"
    restart: unless-stopped
    networks:
      new:
        aliases:
          - verwarmnefitread
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        
  nefit-easy:
    environment:
      - TZ='Europe/Amsterdam'
      - NEFIT_SERIAL_NUMBER=654950243
      - NEFIT_ACCESS_KEY=bxaAMRfNvBJUmD5n
      - NEFIT_PASSWORD=Hoera888
    build: "./nefit-easy"
    restart: unless-stopped
    networks:
      new:
        aliases:
          - nefit-easy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "8000:8000"
        
networks:
  new:
